# Generated by Django 4.1.1 on 2022-10-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('active', models.BooleanField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IP', 'Internship'), ('CO', 'Contract')], max_length=2)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UC', 'Under Consideration'), ('AS', 'Application Submitted'), ('AR', 'Application Rejected'), ('PA', 'Pending Action'), ('AW', 'Application Withdrawn')], default='AS', max_length=2)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.job')),
            ],
        ),
    ]
