# Generated by Django 4.1.1 on 2022-10-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Aviate', max_length=150),
            preserve_default=False,
        ),
    ]
