# Generated by Django 4.1.1 on 2022-10-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_alter_application_applied_on_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
